"""empty message

Revision ID: 0c436d75981f
Revises: aa8d6357b215
Create Date: 2020-01-17 00:43:27.216401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c436d75981f'
down_revision = 'aa8d6357b215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'address')
    # ### end Alembic commands ###
